apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f container-compose.yml convert -n servarr
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: audiobookshelf
  name: audiobookshelf
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: audiobookshelf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f container-compose.yml convert -n servarr
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: audiobookshelf
    spec:
      containers:
        - env:
            - name: TZ
              value: America/Detroit
            - name: user
              value: 13014:13000
          image: ghcr.io/advplyr/audiobookshelf:latest
          name: audiobookshelf
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: audiobookshelf-cm0
            - mountPath: /audiobooks
              name: audiobookshelf-claim1
            - mountPath: /podcasts
              name: audiobookshelf-claim2
      restartPolicy: Always
      volumes:
        - configMap:
            name: audiobookshelf-cm0
          name: audiobookshelf-cm0
        - name: audiobookshelf-claim1
          persistentVolumeClaim:
            claimName: audiobookshelf-claim1
        - name: audiobookshelf-claim2
          persistentVolumeClaim:
            claimName: audiobookshelf-claim2
