apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f container-compose.yml convert -n servarr
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: audiobookshelf
  name: audiobookshelf
  namespace: servarr
spec:
  ports:
    - name: "13378"
      port: 13378
      targetPort: 80
  selector:
    io.kompose.service: audiobookshelf
