apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f container-compose.yml convert -n servarr
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: bazarr
  name: bazarr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f container-compose.yml convert -n servarr
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: bazarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "13000"
            - name: PUID
              value: "13013"
            - name: TZ
              value: America/Detroit
          image: lscr.io/linuxserver/bazarr:latest
          name: bazarr
          ports:
            - containerPort: 6767
              protocol: TCP
      restartPolicy: Always
