---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      # - POSTGRES_PASSWORD=${SONARR__POSTGRES_PASSWORD}
      # - POSTGRES_USER=${SONARR__POSTGRES_USER}
      # - POSTGRES_DB=${SONARR__POSTGRES_DB}
    volumes:
      - ${EZARR_ROOT_DIR}/config/sonarr-config:/config
      - ${EZARR_ROOT_DIR}/data:/data
    ports:
      - "8989:8989"
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${EZARR_ROOT_DIR}/config/radarr-config:/config
      - ${EZARR_ROOT_DIR}/data:/data
    ports:
      - "7878:7878"
    restart: always

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - user=13014:13000
      - TZ=${TIMEZONE}
    volumes:
      - ${EZARR_ROOT_DIR}/config/audiobookshelf:/config
      - ${EZARR_ROOT_DIR}/data/media/audiobooks:/audiobooks
      - ${EZARR_ROOT_DIR}/data/media/podcasts:/podcasts
      - ${EZARR_ROOT_DIR}/data/media/audiobookshelf-metadata:/metadata
    ports:
      - "13378:80"
    restart: always

  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    environment:
      - SECRET_ENCRYPTION_KEY=d3994946f0371c3a043b7e35fde11ab9606f59cd4dc2c7746c5262884e60f1b0
      - AUTH_PROVIDERS=${HOMARR__AUTH_PROVIDERS:-credentials}
      - AUTH_OIDC_ISSUER=${HOMARR__AUTH_OIDC_ISSUER:-}
      - AUTH_OIDC_CLIENT_ID=${HOMARR__AUTH_OIDC_CLIENT_ID:-}
      - AUTH_OIDC_CLIENT_SECRET=${HOMARR__AUTH_OIDC_CLIENT_SECRET:-}
      - AUTH_OIDC_CLIENT_NAME=${HOMARR__AUTH_OIDC_CLIENT_NAME:-OIDC}
        #      - AUTH_OIDC_AUTO_LOGIN=${HOMARR__AUTH_OIDC_AUTO_LOGIN:-false}
        #      - AUTH_OIDC_SCOPE_OVERWRITE=${HOMARR__AUTH_OIDC_SCOPE_OVERWRITE:-openid,email,profile,groups}
        #      - AUTH_OIDC_GROUPS_ATTRIBUTE=${HOMARR__AUTH_OIDC_GROUPS_ATTRIBUTE:-groups}
        #      - AUTH_OIDC_NAME_ATTRIBUTE_OVERWRITE=${HOMARR__AUTH_OIDC_NAME_ATTRIBUTE_OVERWRITE:-}
        #      - AUTH_OIDC_FORCE_USERINFO=${HOMARR__AUTH_OIDC_FORCE_USERINFO:-false}
        #      - AUTH_OIDC_ENABLE_DANGEROUS_ACCOUNT_LINKING=${HOMARR__AUTH_OIDC_ENABLE_DANGEROUS_ACCOUNT_LINKING:-false}
        #      - AUTH_OIDC_NAME_CLAIM=email
    volumes:
      - ${EZARR_ROOT_DIR}/data/homarr/appdata:/appdata
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "7575:7575"
    restart: always

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=13013
      - PGID=13000
      - TZ=${TIMEZONE}
    volumes:
      - ${EZARR_ROOT_DIR}/config/bazarr-config:/config
      - ${EZARR_ROOT_DIR}/data/media:/media
    ports:
      - "6767:6767"
    restart: always

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=13012
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${EZARR_ROOT_DIR}/config/jellyseerr-config:/app/config
    ports:
      - "5056:5055"
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${EZARR_ROOT_DIR}/config/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: always

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    ports:
      - "8191:8191"
    restart: always

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${EZARR_ROOT_DIR}/config/jellyfin-config:/config
      - ${EZARR_ROOT_DIR}/data/media:/data
    ports:
      - "8096:8096"
    restart: always

  # qbittorrent:
  #   image: lscr.io/linuxserver/qbittorrent:latest
  #   container_name: qbittorrent
  #   environment:
  #     - PUID=13007
  #     - PGID=13000
  #     - UMASK=002
  #     - TZ=${TIMEZONE}
  #     - WEBUI_PORT=8080
  #   volumes:
  #     - ${EZARR_ROOT_DIR}/config/qbittorrent-config:/config
  #     - ${EZARR_ROOT_DIR}/data/torrents:/data/torrents
  #   ports:
  #     - "8080:8080"
  #     - "6881:6881"
  #     - "6881:6881/udp"
  #   restart: always

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=13011
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${EZARR_ROOT_DIR}/config/sabnzbd-config:/config
      - ${EZARR_ROOT_DIR}/data/usenet:/data/usenet
    ports:
      - "8081:8080"
    restart: always

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=${TIMEZONE}    # optional: Change to your desired timezone
      - NTFY_BASE_URL=${NTFY_BASE_URL}
      - NTFY_BEHIND_PROXY=true
    volumes:
      - ${EZARR_ROOT_DIR}/data/ntfy:/var/cache/ntfy
      - ${EZARR_ROOT_DIR}/config/ntfy-config:/etc/ntfy
    ports:
      - 8888:80
    restart: always

  postgresql:
    container_name: postgresql
    env_file:
    - .env
    environment:
      POSTGRES_DB: ${AUTHENTIK__PG_DB:-authentik}
      POSTGRES_PASSWORD: ${AUTHENTIK__PG_PASS:?database password required}
      POSTGRES_USER: ${AUTHENTIK__PG_USER:-authentik}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: docker.io/library/postgres:16-alpine
    restart: always
    volumes:
    - ${EZARR_ROOT_DIR}/data/authentik-data/database:/var/lib/postgresql/data

