apiVersion: v1
data:
  AUDIOBOOKSHELF_UID: "13014"
  AUTHENTIK__PG_PASS: New123Pass!!
  AUTHENTIK__SECRET_KEY: New123Pass!!
  AUTHENTIK_EMAIL__FROM: Glorious_Leader@chilini.xyz
  AUTHENTIK_EMAIL__HOST: smtp-relay.brevo.com
  AUTHENTIK_EMAIL__PASSWORD: xsmtpsib-bcc5600c5f67b5703c4e47b213b5596c6e9d0b624d008ec33c35057a9e046a14-MpOkl29feFqRr9u6
  AUTHENTIK_EMAIL__PORT: "587"
  AUTHENTIK_EMAIL__TIMEOUT: "10"
  AUTHENTIK_EMAIL__USE_SSL: "false"
  AUTHENTIK_EMAIL__USE_TLS: "false"
  AUTHENTIK_EMAIL__USERNAME: 3bd8a5001@smtp-brevo.com
  BAZARR_UID: "13013"
  EZARR_ROOT_DIR: /opt/ezarr
  HOMARR__AUTH_OIDC_AUTO_LOGIN: ""
  HOMARR__AUTH_OIDC_CLIENT_ID: 5nixV0Vr13it1RpicWK7paicKbjP84VNHk5xryZv
  HOMARR__AUTH_OIDC_CLIENT_NAME: Authentik
  HOMARR__AUTH_OIDC_CLIENT_SECRET: dzYxMOc1ctOaQg7cITiJlaFmElNbnf0PSIibh6CcXIEu5mMjVkS1z0Y8rdt4k2LvhjI4Uf73IiYoOrFq27lG545wVmAI0gqmqY92nJyYELNad0HK5FfmnrmGexqPK56x
  HOMARR__AUTH_OIDC_ENABLE_DANGEROUS_ACCOUNT_LINKING: ""
  HOMARR__AUTH_OIDC_FORCE_USERINFO: ""
  HOMARR__AUTH_OIDC_GROUPS_ATTRIBUTE: ""
  HOMARR__AUTH_OIDC_ISSUER: https://chilini.xyz/application/o/homarr/
  HOMARR__AUTH_OIDC_NAME_ATTRIBUTE_OVERWRITE: ""
  HOMARR__AUTH_OIDC_SCOPE_OVERWRITE: ""
  HOMARR__AUTH_PROVIDERS: oidc,credentials
  JACKETT_UID: "13008"
  JELLYSEERR_UID: "13012"
  LIDARR_UID: "13003"
  MEDIACENTER_GID: "13000"
  MYLAR_UID: "13005"
  NTFY_BASE_URL: https://ntfy.chilini.xyz
  OVERSEERR_UID: "13009"
  PLEX_CLAIM: ""
  PLEX_UID: "13010"
  PROWLARR_UID: "13006"
  QBITTORRENT_UID: "13007"
  RADARR_UID: "13002"
  READARR_UID: "13004"
  SABNZBD_UID: "13011"
  SONARR__POSTGRES_DB: sonarr
  SONARR__POSTGRES_USER: sonarr
  SONARR_UID: "13001"
  TIMEZONE: America/Detroit
  UID: "1000"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: postgresql-env
  name: env
  namespace: servarr
