apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f container-compose.yml convert -n servarr
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: flaresolverr
  name: flaresolverr
  namespace: servarr
spec:
  ports:
    - name: "8191"
      port: 8191
      targetPort: 8191
  selector:
    io.kompose.service: flaresolverr
