apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f container-compose.yml convert -n servarr
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: homarr
  name: homarr
  namespace: servarr
spec:
  ports:
    - name: "7575"
      port: 7575
      targetPort: 7575
  selector:
    io.kompose.service: homarr
