apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f container-compose.yml convert -n servarr
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: homarr
  name: homarr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: homarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f container-compose.yml convert -n servarr
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: homarr
    spec:
      containers:
        - env:
            - name: AUTH_OIDC_CLIENT_ID
              value: 5nixV0Vr13it1RpicWK7paicKbjP84VNHk5xryZv
            - name: AUTH_OIDC_CLIENT_NAME
              value: Authentik
            - name: AUTH_OIDC_CLIENT_SECRET
              value: dzYxMOc1ctOaQg7cITiJlaFmElNbnf0PSIibh6CcXIEu5mMjVkS1z0Y8rdt4k2LvhjI4Uf73IiYoOrFq27lG545wVmAI0gqmqY92nJyYELNad0HK5FfmnrmGexqPK56x
            - name: AUTH_OIDC_ISSUER
              value: https://chilini.xyz/application/o/homarr/
            - name: AUTH_PROVIDERS
              value: oidc,credentials
            - name: SECRET_ENCRYPTION_KEY
              value: d3994946f0371c3a043b7e35fde11ab9606f59cd4dc2c7746c5262884e60f1b0
          image: ghcr.io/homarr-labs/homarr:latest
          name: homarr
          ports:
            - containerPort: 7575
              protocol: TCP
      restartPolicy: Always
