apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f container-compose.yml convert -n servarr
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: jellyseerr
  name: jellyseerr
  namespace: servarr
spec:
  ports:
    - name: "5056"
      port: 5056
      targetPort: 5055
  selector:
    io.kompose.service: jellyseerr
