apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f container-compose.yml convert -n servarr
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: postgresql
  name: postgresql
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f container-compose.yml convert -n servarr
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: postgresql
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: authentik
            - name: POSTGRES_PASSWORD
              value: New123Pass!!
            - name: POSTGRES_USER
              value: authentik
          envFrom:
            - configMapRef:
                name: env
          image: docker.io/library/postgres:16-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
          name: postgresql
      restartPolicy: Always
