apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f container-compose.yml convert -n servarr
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: prowlarr
  name: prowlarr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f container-compose.yml convert -n servarr
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: prowlarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "13000"
            - name: PUID
              value: "13006"
            - name: TZ
              value: America/Detroit
            - name: UMASK
              value: "002"
          image: lscr.io/linuxserver/prowlarr:develop
          name: prowlarr
          ports:
            - containerPort: 9696
              protocol: TCP
      restartPolicy: Always
