apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f container-compose.yml convert -n servarr
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: sabnzbd
  name: sabnzbd
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sabnzbd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f container-compose.yml convert -n servarr
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: sabnzbd
    spec:
      containers:
        - env:
            - name: PGID
              value: "13000"
            - name: PUID
              value: "13011"
            - name: TZ
              value: America/Detroit
            - name: UMASK
              value: "002"
          image: lscr.io/linuxserver/sabnzbd:latest
          name: sabnzbd
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /data/usenet
              name: sabnzbd-claim1
      restartPolicy: Always
      volumes:
        - name: sabnzbd-claim1
          persistentVolumeClaim:
            claimName: sabnzbd-claim1
